# Generated by Django 3.1.2 on 2020-10-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_todo', '0002_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
